CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(254) NOT NULL UNIQUE,
  password_hash text NOT NULL,
  verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  verification_hash varchar(64) UNIQUE,
  verification_expires timestamptz,
  verification_sent_at timestamptz
);
CREATE TABLE IF NOT EXISTS sessions (
  token_hash varchar(64) PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title varchar(200) NOT NULL,
  event_date date NOT NULL,
  time_zone varchar(100) NOT NULL,
  recurring boolean NOT NULL DEFAULT false,
  importance integer NOT NULL CHECK (importance BETWEEN 1 AND 10),
  note varchar(200) NOT NULL DEFAULT '',
  remind_month boolean NOT NULL DEFAULT false,
  remind_week boolean NOT NULL DEFAULT false,
  remind_day boolean NOT NULL DEFAULT false,
  remind_today boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS events_owner ON events(user_id, event_date);
CREATE TABLE IF NOT EXISTS deliveries (
  event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  occurrence date NOT NULL,
  kind varchar(10) NOT NULL,
  state varchar(10) NOT NULL CHECK (state IN ('sending','sent','failed')),
  lease_until timestamptz NOT NULL,
  attempts integer NOT NULL DEFAULT 1,
  sent_at timestamptz,
  PRIMARY KEY(event_id, occurrence, kind)
);
CREATE TABLE IF NOT EXISTS rate_limits (
  key varchar(64) PRIMARY KEY,
  hits integer NOT NULL,
  expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS rate_limits_expiry ON rate_limits(expires_at);
