// <auto-generated />
using System;
using DatesAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatesAPI.Migrations
{
    [DbContext(typeof(DateDetailsContext))]
    [Migration("20260919053904_AddEventTimeZones")]
    partial class AddEventTimeZones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatesAPI.Models.DateDetails", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DateId"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventNote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitialLoggedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OneDayReminderSentFor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OneMonthReminderSentFor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OneWeekReminderSentFor")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReminderOneDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ReminderOneMonth")
                        .HasColumnType("bit");

                    b.Property<bool>("ReminderOneWeek")
                        .HasColumnType("bit");

                    b.Property<bool>("ReminderSameDay")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SameDayReminderSentFor")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.ToTable("DateDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
